/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;


/**
 * ChargeOrderResponseChannel
 */
@JsonPropertyOrder({
  ChargeOrderResponseChannel.JSON_PROPERTY_SEGMENT,
  ChargeOrderResponseChannel.JSON_PROPERTY_CHECKOUT_REQUEST_ID,
  ChargeOrderResponseChannel.JSON_PROPERTY_CHECKOUT_REQUEST_TYPE,
  ChargeOrderResponseChannel.JSON_PROPERTY_ID
})
@JsonTypeName("charge_order_response_channel")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class ChargeOrderResponseChannel {
  public static final String JSON_PROPERTY_SEGMENT = "segment";
  private String segment;

  public static final String JSON_PROPERTY_CHECKOUT_REQUEST_ID = "checkout_request_id";
  private String checkoutRequestId;

  public static final String JSON_PROPERTY_CHECKOUT_REQUEST_TYPE = "checkout_request_type";
  private String checkoutRequestType;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public ChargeOrderResponseChannel() { 
  }

  public ChargeOrderResponseChannel segment(String segment) {
    this.segment = segment;
    return this;
  }

   /**
   * Get segment
   * @return segment
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEGMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSegment() {
    return segment;
  }


  @JsonProperty(JSON_PROPERTY_SEGMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSegment(String segment) {
    this.segment = segment;
  }


  public ChargeOrderResponseChannel checkoutRequestId(String checkoutRequestId) {
    this.checkoutRequestId = checkoutRequestId;
    return this;
  }

   /**
   * Get checkoutRequestId
   * @return checkoutRequestId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECKOUT_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCheckoutRequestId() {
    return checkoutRequestId;
  }


  @JsonProperty(JSON_PROPERTY_CHECKOUT_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckoutRequestId(String checkoutRequestId) {
    this.checkoutRequestId = checkoutRequestId;
  }


  public ChargeOrderResponseChannel checkoutRequestType(String checkoutRequestType) {
    this.checkoutRequestType = checkoutRequestType;
    return this;
  }

   /**
   * Get checkoutRequestType
   * @return checkoutRequestType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECKOUT_REQUEST_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCheckoutRequestType() {
    return checkoutRequestType;
  }


  @JsonProperty(JSON_PROPERTY_CHECKOUT_REQUEST_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckoutRequestType(String checkoutRequestType) {
    this.checkoutRequestType = checkoutRequestType;
  }


  public ChargeOrderResponseChannel id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  /**
   * Return true if this charge_order_response_channel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargeOrderResponseChannel chargeOrderResponseChannel = (ChargeOrderResponseChannel) o;
    return Objects.equals(this.segment, chargeOrderResponseChannel.segment) &&
        Objects.equals(this.checkoutRequestId, chargeOrderResponseChannel.checkoutRequestId) &&
        Objects.equals(this.checkoutRequestType, chargeOrderResponseChannel.checkoutRequestType) &&
        Objects.equals(this.id, chargeOrderResponseChannel.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(segment, checkoutRequestId, checkoutRequestType, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargeOrderResponseChannel {\n");
    sb.append("    segment: ").append(toIndentedString(segment)).append("\n");
    sb.append("    checkoutRequestId: ").append(toIndentedString(checkoutRequestId)).append("\n");
    sb.append("    checkoutRequestType: ").append(toIndentedString(checkoutRequestType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
