/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.digitalfemsa.JSON;

import javax.ws.rs.core.GenericType;
import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
@JsonDeserialize(using = ChargeResponsePaymentMethod.ChargeResponsePaymentMethodDeserializer.class)
@JsonSerialize(using = ChargeResponsePaymentMethod.ChargeResponsePaymentMethodSerializer.class)
public class ChargeResponsePaymentMethod extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ChargeResponsePaymentMethod.class.getName());

    public static class ChargeResponsePaymentMethodSerializer extends StdSerializer<ChargeResponsePaymentMethod> {
        public ChargeResponsePaymentMethodSerializer(Class<ChargeResponsePaymentMethod> t) {
            super(t);
        }

        public ChargeResponsePaymentMethodSerializer() {
            this(null);
        }

        @Override
        public void serialize(ChargeResponsePaymentMethod value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class ChargeResponsePaymentMethodDeserializer extends StdDeserializer<ChargeResponsePaymentMethod> {
        public ChargeResponsePaymentMethodDeserializer() {
            this(ChargeResponsePaymentMethod.class);
        }

        public ChargeResponsePaymentMethodDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public ChargeResponsePaymentMethod deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            ChargeResponsePaymentMethod newChargeResponsePaymentMethod = new ChargeResponsePaymentMethod();
            Map<String, Object> result2 = tree.traverse(jp.getCodec()).readValueAs(new TypeReference<Map<String, Object>>() {});
            String discriminatorValue = (String)result2.get("object");
            switch (discriminatorValue) {
                case "payment_method_cash":
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PaymentMethodCash.class);
                    newChargeResponsePaymentMethod.setActualInstance(deserialized);
                    return newChargeResponsePaymentMethod;
                default:
                    log.log(Level.WARNING, String.format("Failed to lookup discriminator value `%s` for ChargeResponsePaymentMethod. Possible values: payment_method_cash", discriminatorValue));
            }

            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize PaymentMethodCash
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PaymentMethodCash.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PaymentMethodCash'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PaymentMethodCash'", e);
            }

            if (match == 1) {
                ChargeResponsePaymentMethod ret = new ChargeResponsePaymentMethod();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for ChargeResponsePaymentMethod: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public ChargeResponsePaymentMethod getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "ChargeResponsePaymentMethod cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<>();

    public ChargeResponsePaymentMethod() {
        super("oneOf", Boolean.FALSE);
    }

    public ChargeResponsePaymentMethod(PaymentMethodCash o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("PaymentMethodCash", new GenericType<PaymentMethodCash>() {
        });
        JSON.registerDescendants(ChargeResponsePaymentMethod.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<>();
        mappings.put("payment_method_cash", PaymentMethodCash.class);
        mappings.put("charge_response_payment_method", ChargeResponsePaymentMethod.class);
        JSON.registerDiscriminator(ChargeResponsePaymentMethod.class, "object", mappings);
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return ChargeResponsePaymentMethod.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * PaymentMethodCash
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(PaymentMethodCash.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be PaymentMethodCash");
    }

    /**
     * Get the actual instance, which can be the following:
     * PaymentMethodCash
     *
     * @return The actual instance (PaymentMethodCash)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PaymentMethodCash`. If the actual instance is not `PaymentMethodCash`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PaymentMethodCash`
     * @throws ClassCastException if the instance is not `PaymentMethodCash`
     */
    public PaymentMethodCash getPaymentMethodCash() throws ClassCastException {
        return (PaymentMethodCash)super.getActualInstance();
    }

}
