/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;


/**
 * Customer create request.
 */
@JsonPropertyOrder({
  Customer.JSON_PROPERTY_NAME,
  Customer.JSON_PROPERTY_EMAIL,
  Customer.JSON_PROPERTY_PHONE,
  Customer.JSON_PROPERTY_CORPORATE,
  Customer.JSON_PROPERTY_CUSTOM_REFERENCE,
  Customer.JSON_PROPERTY_REFERRER,
  Customer.JSON_PROPERTY_METADATA,
  Customer.JSON_PROPERTY_FISCAL_ENTITIES,
  Customer.JSON_PROPERTY_SHIPPING_CONTACTS,
  Customer.JSON_PROPERTY_PAYMENT_SOURCES
})
@JsonTypeName("customer")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class Customer {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  public static final String JSON_PROPERTY_CORPORATE = "corporate";
  private Boolean corporate = false;

  public static final String JSON_PROPERTY_CUSTOM_REFERENCE = "custom_reference";
  private String customReference;

  public static final String JSON_PROPERTY_REFERRER = "referrer";
  private String referrer;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_FISCAL_ENTITIES = "fiscal_entities";
  private List<CustomerFiscalEntitiesRequest> fiscalEntities;

  public static final String JSON_PROPERTY_SHIPPING_CONTACTS = "shipping_contacts";
  private List<CustomerShippingContacts> shippingContacts;

  public static final String JSON_PROPERTY_PAYMENT_SOURCES = "payment_sources";
  private List<CustomerPaymentSourcesInner> paymentSources;

  public Customer() { 
  }

  public Customer name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Customer&#39;s name.
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public Customer email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Customer email address.
   * @return email
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(String email) {
    this.email = email;
  }


  public Customer phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Customer phone number.
   * @return phone
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(String phone) {
    this.phone = phone;
  }


  public Customer corporate(Boolean corporate) {
    this.corporate = corporate;
    return this;
  }

   /**
   * Indicates whether the customer email is corporate.
   * @return corporate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CORPORATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCorporate() {
    return corporate;
  }


  @JsonProperty(JSON_PROPERTY_CORPORATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCorporate(Boolean corporate) {
    this.corporate = corporate;
  }


  public Customer customReference(String customReference) {
    this.customReference = customReference;
    return this;
  }

   /**
   * Merchant-defined reference used to identify the customer in your system.
   * @return customReference
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomReference() {
    return customReference;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomReference(String customReference) {
    this.customReference = customReference;
  }


  public Customer referrer(String referrer) {
    this.referrer = referrer;
    return this;
  }

   /**
   * Referrer value (if applicable).
   * @return referrer
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERRER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferrer() {
    return referrer;
  }


  @JsonProperty(JSON_PROPERTY_REFERRER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferrer(String referrer) {
    this.referrer = referrer;
  }


  public Customer metadata(Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public Customer putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Arbitrary metadata associated with the customer.
   * @return metadata
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public Customer fiscalEntities(List<CustomerFiscalEntitiesRequest> fiscalEntities) {
    this.fiscalEntities = fiscalEntities;
    return this;
  }

  public Customer addFiscalEntitiesItem(CustomerFiscalEntitiesRequest fiscalEntitiesItem) {
    if (this.fiscalEntities == null) {
      this.fiscalEntities = new ArrayList<>();
    }
    this.fiscalEntities.add(fiscalEntitiesItem);
    return this;
  }

   /**
   * Customer fiscal entities to be created with the customer (optional).
   * @return fiscalEntities
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FISCAL_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomerFiscalEntitiesRequest> getFiscalEntities() {
    return fiscalEntities;
  }


  @JsonProperty(JSON_PROPERTY_FISCAL_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiscalEntities(List<CustomerFiscalEntitiesRequest> fiscalEntities) {
    this.fiscalEntities = fiscalEntities;
  }


  public Customer shippingContacts(List<CustomerShippingContacts> shippingContacts) {
    this.shippingContacts = shippingContacts;
    return this;
  }

  public Customer addShippingContactsItem(CustomerShippingContacts shippingContactsItem) {
    if (this.shippingContacts == null) {
      this.shippingContacts = new ArrayList<>();
    }
    this.shippingContacts.add(shippingContactsItem);
    return this;
  }

   /**
   * Customer shipping contacts to be created with the customer (optional).
   * @return shippingContacts
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_CONTACTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomerShippingContacts> getShippingContacts() {
    return shippingContacts;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_CONTACTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingContacts(List<CustomerShippingContacts> shippingContacts) {
    this.shippingContacts = shippingContacts;
  }


  public Customer paymentSources(List<CustomerPaymentSourcesInner> paymentSources) {
    this.paymentSources = paymentSources;
    return this;
  }

  public Customer addPaymentSourcesItem(CustomerPaymentSourcesInner paymentSourcesItem) {
    if (this.paymentSources == null) {
      this.paymentSources = new ArrayList<>();
    }
    this.paymentSources.add(paymentSourcesItem);
    return this;
  }

   /**
   * Customer payment sources to be created with the customer (optional).
   * @return paymentSources
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomerPaymentSourcesInner> getPaymentSources() {
    return paymentSources;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentSources(List<CustomerPaymentSourcesInner> paymentSources) {
    this.paymentSources = paymentSources;
  }


  /**
   * Return true if this customer object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.name, customer.name) &&
        Objects.equals(this.email, customer.email) &&
        Objects.equals(this.phone, customer.phone) &&
        Objects.equals(this.corporate, customer.corporate) &&
        Objects.equals(this.customReference, customer.customReference) &&
        Objects.equals(this.referrer, customer.referrer) &&
        Objects.equals(this.metadata, customer.metadata) &&
        Objects.equals(this.fiscalEntities, customer.fiscalEntities) &&
        Objects.equals(this.shippingContacts, customer.shippingContacts) &&
        Objects.equals(this.paymentSources, customer.paymentSources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, email, phone, corporate, customReference, referrer, metadata, fiscalEntities, shippingContacts, paymentSources);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    corporate: ").append(toIndentedString(corporate)).append("\n");
    sb.append("    customReference: ").append(toIndentedString(customReference)).append("\n");
    sb.append("    referrer: ").append(toIndentedString(referrer)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    fiscalEntities: ").append(toIndentedString(fiscalEntities)).append("\n");
    sb.append("    shippingContacts: ").append(toIndentedString(shippingContacts)).append("\n");
    sb.append("    paymentSources: ").append(toIndentedString(paymentSources)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
