/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.digitalfemsa.JSON;

import javax.ws.rs.core.GenericType;
import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
@JsonDeserialize(using = CustomerPaymentMethodsRequest.CustomerPaymentMethodsRequestDeserializer.class)
@JsonSerialize(using = CustomerPaymentMethodsRequest.CustomerPaymentMethodsRequestSerializer.class)
public class CustomerPaymentMethodsRequest extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CustomerPaymentMethodsRequest.class.getName());

    public static class CustomerPaymentMethodsRequestSerializer extends StdSerializer<CustomerPaymentMethodsRequest> {
        public CustomerPaymentMethodsRequestSerializer(Class<CustomerPaymentMethodsRequest> t) {
            super(t);
        }

        public CustomerPaymentMethodsRequestSerializer() {
            this(null);
        }

        @Override
        public void serialize(CustomerPaymentMethodsRequest value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class CustomerPaymentMethodsRequestDeserializer extends StdDeserializer<CustomerPaymentMethodsRequest> {
        public CustomerPaymentMethodsRequestDeserializer() {
            this(CustomerPaymentMethodsRequest.class);
        }

        public CustomerPaymentMethodsRequestDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public CustomerPaymentMethodsRequest deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize PaymentMethodCashRequest
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PaymentMethodCashRequest.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PaymentMethodCashRequest'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PaymentMethodCashRequest'", e);
            }

            if (match == 1) {
                CustomerPaymentMethodsRequest ret = new CustomerPaymentMethodsRequest();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for CustomerPaymentMethodsRequest: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public CustomerPaymentMethodsRequest getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "CustomerPaymentMethodsRequest cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<>();

    public CustomerPaymentMethodsRequest() {
        super("oneOf", Boolean.FALSE);
    }

    public CustomerPaymentMethodsRequest(PaymentMethodCashRequest o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("PaymentMethodCashRequest", new GenericType<PaymentMethodCashRequest>() {
        });
        JSON.registerDescendants(CustomerPaymentMethodsRequest.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return CustomerPaymentMethodsRequest.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * PaymentMethodCashRequest
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(PaymentMethodCashRequest.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be PaymentMethodCashRequest");
    }

    /**
     * Get the actual instance, which can be the following:
     * PaymentMethodCashRequest
     *
     * @return The actual instance (PaymentMethodCashRequest)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PaymentMethodCashRequest`. If the actual instance is not `PaymentMethodCashRequest`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PaymentMethodCashRequest`
     * @throws ClassCastException if the instance is not `PaymentMethodCashRequest`
     */
    public PaymentMethodCashRequest getPaymentMethodCashRequest() throws ClassCastException {
        return (PaymentMethodCashRequest)super.getActualInstance();
    }

}
