/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;


/**
 * Order update payload. Only supported fields can be modified.
 */
@JsonPropertyOrder({
  OrderUpdateRequest.JSON_PROPERTY_STATUS,
  OrderUpdateRequest.JSON_PROPERTY_CURRENCY,
  OrderUpdateRequest.JSON_PROPERTY_CUSTOMER_INFO,
  OrderUpdateRequest.JSON_PROPERTY_LINE_ITEMS,
  OrderUpdateRequest.JSON_PROPERTY_SHIPPING_LINES,
  OrderUpdateRequest.JSON_PROPERTY_TAX_LINES,
  OrderUpdateRequest.JSON_PROPERTY_DISCOUNT_LINES,
  OrderUpdateRequest.JSON_PROPERTY_METADATA,
  OrderUpdateRequest.JSON_PROPERTY_RETURN_URL,
  OrderUpdateRequest.JSON_PROPERTY_CHARGES,
  OrderUpdateRequest.JSON_PROPERTY_SHIPPING_CONTACT_ID,
  OrderUpdateRequest.JSON_PROPERTY_SHIPPING_CONTACT,
  OrderUpdateRequest.JSON_PROPERTY_FISCAL_ENTITY_ID,
  OrderUpdateRequest.JSON_PROPERTY_FISCAL_ENTITY
})
@JsonTypeName("order_update_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class OrderUpdateRequest {
  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_CUSTOMER_INFO = "customer_info";
  private CustomerInfo customerInfo;

  public static final String JSON_PROPERTY_LINE_ITEMS = "line_items";
  private List<Product> lineItems = new ArrayList<>();

  public static final String JSON_PROPERTY_SHIPPING_LINES = "shipping_lines";
  private List<ShippingRequest> shippingLines = new ArrayList<>();

  public static final String JSON_PROPERTY_TAX_LINES = "tax_lines";
  private List<OrderTaxRequest> taxLines = new ArrayList<>();

  public static final String JSON_PROPERTY_DISCOUNT_LINES = "discount_lines";
  private List<OrderDiscountLinesRequest> discountLines = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_RETURN_URL = "return_url";
  private String returnUrl;

  public static final String JSON_PROPERTY_CHARGES = "charges";
  private List<ChargeRequest> charges = new ArrayList<>();

  public static final String JSON_PROPERTY_SHIPPING_CONTACT_ID = "shipping_contact_id";
  private String shippingContactId;

  public static final String JSON_PROPERTY_SHIPPING_CONTACT = "shipping_contact";
  private CustomerShippingContacts shippingContact;

  public static final String JSON_PROPERTY_FISCAL_ENTITY_ID = "fiscal_entity_id";
  private String fiscalEntityId;

  public static final String JSON_PROPERTY_FISCAL_ENTITY = "fiscal_entity";
  private OrderUpdateFiscalEntityRequest fiscalEntity;

  public OrderUpdateRequest() { 
  }

  public OrderUpdateRequest status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Order status update. Allowed values depend on server-side validations.
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public OrderUpdateRequest currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency used for the order. Uses ISO 4217 (3-letter code). Allowed values depend on server-side validations.
   * @return currency
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public OrderUpdateRequest customerInfo(CustomerInfo customerInfo) {
    this.customerInfo = customerInfo;
    return this;
  }

   /**
   * Get customerInfo
   * @return customerInfo
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerInfo getCustomerInfo() {
    return customerInfo;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerInfo(CustomerInfo customerInfo) {
    this.customerInfo = customerInfo;
  }


  public OrderUpdateRequest lineItems(List<Product> lineItems) {
    this.lineItems = lineItems;
    return this;
  }

  public OrderUpdateRequest addLineItemsItem(Product lineItemsItem) {
    if (this.lineItems == null) {
      this.lineItems = new ArrayList<>();
    }
    this.lineItems.add(lineItemsItem);
    return this;
  }

   /**
   * List of products sold in the order.
   * @return lineItems
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINE_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Product> getLineItems() {
    return lineItems;
  }


  @JsonProperty(JSON_PROPERTY_LINE_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLineItems(List<Product> lineItems) {
    this.lineItems = lineItems;
  }


  public OrderUpdateRequest shippingLines(List<ShippingRequest> shippingLines) {
    this.shippingLines = shippingLines;
    return this;
  }

  public OrderUpdateRequest addShippingLinesItem(ShippingRequest shippingLinesItem) {
    if (this.shippingLines == null) {
      this.shippingLines = new ArrayList<>();
    }
    this.shippingLines.add(shippingLinesItem);
    return this;
  }

   /**
   * List of shipping costs applied to the order.
   * @return shippingLines
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ShippingRequest> getShippingLines() {
    return shippingLines;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingLines(List<ShippingRequest> shippingLines) {
    this.shippingLines = shippingLines;
  }


  public OrderUpdateRequest taxLines(List<OrderTaxRequest> taxLines) {
    this.taxLines = taxLines;
    return this;
  }

  public OrderUpdateRequest addTaxLinesItem(OrderTaxRequest taxLinesItem) {
    if (this.taxLines == null) {
      this.taxLines = new ArrayList<>();
    }
    this.taxLines.add(taxLinesItem);
    return this;
  }

   /**
   * Get taxLines
   * @return taxLines
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OrderTaxRequest> getTaxLines() {
    return taxLines;
  }


  @JsonProperty(JSON_PROPERTY_TAX_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxLines(List<OrderTaxRequest> taxLines) {
    this.taxLines = taxLines;
  }


  public OrderUpdateRequest discountLines(List<OrderDiscountLinesRequest> discountLines) {
    this.discountLines = discountLines;
    return this;
  }

  public OrderUpdateRequest addDiscountLinesItem(OrderDiscountLinesRequest discountLinesItem) {
    if (this.discountLines == null) {
      this.discountLines = new ArrayList<>();
    }
    this.discountLines.add(discountLinesItem);
    return this;
  }

   /**
   * List of discounts applied to the order.
   * @return discountLines
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCOUNT_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OrderDiscountLinesRequest> getDiscountLines() {
    return discountLines;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountLines(List<OrderDiscountLinesRequest> discountLines) {
    this.discountLines = discountLines;
  }


  public OrderUpdateRequest metadata(Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public OrderUpdateRequest putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Additional information attached to the order.
   * @return metadata
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public OrderUpdateRequest returnUrl(String returnUrl) {
    this.returnUrl = returnUrl;
    return this;
  }

   /**
   * URL to redirect the customer after completing the flow (when applicable).
   * @return returnUrl
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETURN_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReturnUrl() {
    return returnUrl;
  }


  @JsonProperty(JSON_PROPERTY_RETURN_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReturnUrl(String returnUrl) {
    this.returnUrl = returnUrl;
  }


  public OrderUpdateRequest charges(List<ChargeRequest> charges) {
    this.charges = charges;
    return this;
  }

  public OrderUpdateRequest addChargesItem(ChargeRequest chargesItem) {
    if (this.charges == null) {
      this.charges = new ArrayList<>();
    }
    this.charges.add(chargesItem);
    return this;
  }

   /**
   * Add new charges to the order. Subject to server-side validations (for example, maximum charges rules). 
   * @return charges
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHARGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ChargeRequest> getCharges() {
    return charges;
  }


  @JsonProperty(JSON_PROPERTY_CHARGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCharges(List<ChargeRequest> charges) {
    this.charges = charges;
  }


  public OrderUpdateRequest shippingContactId(String shippingContactId) {
    this.shippingContactId = shippingContactId;
    return this;
  }

   /**
   * References an existing customer shipping contact.
   * @return shippingContactId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_CONTACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShippingContactId() {
    return shippingContactId;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_CONTACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingContactId(String shippingContactId) {
    this.shippingContactId = shippingContactId;
  }


  public OrderUpdateRequest shippingContact(CustomerShippingContacts shippingContact) {
    this.shippingContact = shippingContact;
    return this;
  }

   /**
   * Get shippingContact
   * @return shippingContact
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerShippingContacts getShippingContact() {
    return shippingContact;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingContact(CustomerShippingContacts shippingContact) {
    this.shippingContact = shippingContact;
  }


  public OrderUpdateRequest fiscalEntityId(String fiscalEntityId) {
    this.fiscalEntityId = fiscalEntityId;
    return this;
  }

   /**
   * References an existing customer fiscal entity.
   * @return fiscalEntityId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FISCAL_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFiscalEntityId() {
    return fiscalEntityId;
  }


  @JsonProperty(JSON_PROPERTY_FISCAL_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiscalEntityId(String fiscalEntityId) {
    this.fiscalEntityId = fiscalEntityId;
  }


  public OrderUpdateRequest fiscalEntity(OrderUpdateFiscalEntityRequest fiscalEntity) {
    this.fiscalEntity = fiscalEntity;
    return this;
  }

   /**
   * Get fiscalEntity
   * @return fiscalEntity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FISCAL_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrderUpdateFiscalEntityRequest getFiscalEntity() {
    return fiscalEntity;
  }


  @JsonProperty(JSON_PROPERTY_FISCAL_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiscalEntity(OrderUpdateFiscalEntityRequest fiscalEntity) {
    this.fiscalEntity = fiscalEntity;
  }


  /**
   * Return true if this order_update_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderUpdateRequest orderUpdateRequest = (OrderUpdateRequest) o;
    return Objects.equals(this.status, orderUpdateRequest.status) &&
        Objects.equals(this.currency, orderUpdateRequest.currency) &&
        Objects.equals(this.customerInfo, orderUpdateRequest.customerInfo) &&
        Objects.equals(this.lineItems, orderUpdateRequest.lineItems) &&
        Objects.equals(this.shippingLines, orderUpdateRequest.shippingLines) &&
        Objects.equals(this.taxLines, orderUpdateRequest.taxLines) &&
        Objects.equals(this.discountLines, orderUpdateRequest.discountLines) &&
        Objects.equals(this.metadata, orderUpdateRequest.metadata) &&
        Objects.equals(this.returnUrl, orderUpdateRequest.returnUrl) &&
        Objects.equals(this.charges, orderUpdateRequest.charges) &&
        Objects.equals(this.shippingContactId, orderUpdateRequest.shippingContactId) &&
        Objects.equals(this.shippingContact, orderUpdateRequest.shippingContact) &&
        Objects.equals(this.fiscalEntityId, orderUpdateRequest.fiscalEntityId) &&
        Objects.equals(this.fiscalEntity, orderUpdateRequest.fiscalEntity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, currency, customerInfo, lineItems, shippingLines, taxLines, discountLines, metadata, returnUrl, charges, shippingContactId, shippingContact, fiscalEntityId, fiscalEntity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderUpdateRequest {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    customerInfo: ").append(toIndentedString(customerInfo)).append("\n");
    sb.append("    lineItems: ").append(toIndentedString(lineItems)).append("\n");
    sb.append("    shippingLines: ").append(toIndentedString(shippingLines)).append("\n");
    sb.append("    taxLines: ").append(toIndentedString(taxLines)).append("\n");
    sb.append("    discountLines: ").append(toIndentedString(discountLines)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    returnUrl: ").append(toIndentedString(returnUrl)).append("\n");
    sb.append("    charges: ").append(toIndentedString(charges)).append("\n");
    sb.append("    shippingContactId: ").append(toIndentedString(shippingContactId)).append("\n");
    sb.append("    shippingContact: ").append(toIndentedString(shippingContact)).append("\n");
    sb.append("    fiscalEntityId: ").append(toIndentedString(fiscalEntityId)).append("\n");
    sb.append("    fiscalEntity: ").append(toIndentedString(fiscalEntity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
