/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Objects;


/**
 * OrderRefundRequest
 */
@JsonPropertyOrder({
  OrderRefundRequest.JSON_PROPERTY_AMOUNT,
  OrderRefundRequest.JSON_PROPERTY_CHARGE_ID,
  OrderRefundRequest.JSON_PROPERTY_REASON,
  OrderRefundRequest.JSON_PROPERTY_EXPIRES_AT
})
@JsonTypeName("orderRefund_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class OrderRefundRequest {
  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Long amount;

  public static final String JSON_PROPERTY_CHARGE_ID = "charge_id";
  private String chargeId;

  /**
   * Refund reason. If not provided, the API uses a default reason.
   */
  public enum ReasonEnum {
    REQUESTED_BY_CLIENT("requested_by_client"),
    
    CANNOT_BE_FULFILLED("cannot_be_fulfilled"),
    
    DUPLICATED_TRANSACTION("duplicated_transaction"),
    
    SUSPECTED_FRAUD("suspected_fraud"),
    
    OTHER("other");

    private String value;

    ReasonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReasonEnum fromValue(String value) {
      for (ReasonEnum b : ReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REASON = "reason";
  private ReasonEnum reason;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  private Long expiresAt;

  public OrderRefundRequest() { 
  }

  public OrderRefundRequest amount(Long amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Amount to refund. If not provided, the API refunds the refundable amount of the selected charge.
   * minimum: 1
   * @return amount
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(Long amount) {
    this.amount = amount;
  }


  public OrderRefundRequest chargeId(String chargeId) {
    this.chargeId = chargeId;
    return this;
  }

   /**
   * Charge ID to refund. If not provided, the API selects a refundable charge from the order.
   * @return chargeId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHARGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChargeId() {
    return chargeId;
  }


  @JsonProperty(JSON_PROPERTY_CHARGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargeId(String chargeId) {
    this.chargeId = chargeId;
  }


  public OrderRefundRequest reason(ReasonEnum reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Refund reason. If not provided, the API uses a default reason.
   * @return reason
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ReasonEnum getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReason(ReasonEnum reason) {
    this.reason = reason;
  }


  public OrderRefundRequest expiresAt(Long expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Expiration timestamp for cash refunds (must be within the allowed range configured by the API).
   * @return expiresAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(Long expiresAt) {
    this.expiresAt = expiresAt;
  }


  /**
   * Return true if this orderRefund_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRefundRequest orderRefundRequest = (OrderRefundRequest) o;
    return Objects.equals(this.amount, orderRefundRequest.amount) &&
        Objects.equals(this.chargeId, orderRefundRequest.chargeId) &&
        Objects.equals(this.reason, orderRefundRequest.reason) &&
        Objects.equals(this.expiresAt, orderRefundRequest.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, chargeId, reason, expiresAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRefundRequest {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    chargeId: ").append(toIndentedString(chargeId)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
