/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * A transfer represents the action of sending an amount to a business bank account including the status, amount and destination used to make the transfer.
 */
@JsonPropertyOrder({
  TransfersResponse.JSON_PROPERTY_ID,
  TransfersResponse.JSON_PROPERTY_OBJECT,
  TransfersResponse.JSON_PROPERTY_AMOUNT,
  TransfersResponse.JSON_PROPERTY_CREATED_AT,
  TransfersResponse.JSON_PROPERTY_CURRENCY,
  TransfersResponse.JSON_PROPERTY_LIVEMODE,
  TransfersResponse.JSON_PROPERTY_STATUS,
  TransfersResponse.JSON_PROPERTY_STATEMENT_REFERENCE,
  TransfersResponse.JSON_PROPERTY_STATEMENT_DESCRIPTION,
  TransfersResponse.JSON_PROPERTY_DESTINATION,
  TransfersResponse.JSON_PROPERTY_FEE,
  TransfersResponse.JSON_PROPERTY_CAPTURE_AMOUNT,
  TransfersResponse.JSON_PROPERTY_CAPTURE_FEE,
  TransfersResponse.JSON_PROPERTY_CAPTURE_NET,
  TransfersResponse.JSON_PROPERTY_REFUND_AMOUNT,
  TransfersResponse.JSON_PROPERTY_REFUND_FEE,
  TransfersResponse.JSON_PROPERTY_REFUND_NET,
  TransfersResponse.JSON_PROPERTY_PAYOUT_AMOUNT,
  TransfersResponse.JSON_PROPERTY_PAYOUT_FEE,
  TransfersResponse.JSON_PROPERTY_PAYOUT_NET,
  TransfersResponse.JSON_PROPERTY_TRANSACTIONS
})
@JsonTypeName("transfers_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class TransfersResponse {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_OBJECT = "object";
  private String _object;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Long amount;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private Long createdAt;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_LIVEMODE = "livemode";
  private Boolean livemode;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_STATEMENT_REFERENCE = "statement_reference";
  private String statementReference;

  public static final String JSON_PROPERTY_STATEMENT_DESCRIPTION = "statement_description";
  private String statementDescription;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  private TransfersResponseDestination destination;

  public static final String JSON_PROPERTY_FEE = "fee";
  private Long fee;

  public static final String JSON_PROPERTY_CAPTURE_AMOUNT = "capture_amount";
  private Long captureAmount;

  public static final String JSON_PROPERTY_CAPTURE_FEE = "capture_fee";
  private Long captureFee;

  public static final String JSON_PROPERTY_CAPTURE_NET = "capture_net";
  private Long captureNet;

  public static final String JSON_PROPERTY_REFUND_AMOUNT = "refund_amount";
  private Long refundAmount;

  public static final String JSON_PROPERTY_REFUND_FEE = "refund_fee";
  private Long refundFee;

  public static final String JSON_PROPERTY_REFUND_NET = "refund_net";
  private Long refundNet;

  public static final String JSON_PROPERTY_PAYOUT_AMOUNT = "payout_amount";
  private Long payoutAmount;

  public static final String JSON_PROPERTY_PAYOUT_FEE = "payout_fee";
  private Long payoutFee;

  public static final String JSON_PROPERTY_PAYOUT_NET = "payout_net";
  private Long payoutNet;

  public static final String JSON_PROPERTY_TRANSACTIONS = "transactions";
  private List<Object> transactions;

  public TransfersResponse() { 
  }

  public TransfersResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the transfer.
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public TransfersResponse _object(String _object) {
    this._object = _object;
    return this;
  }

   /**
   * Object name, which is transfer.
   * @return _object
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(String _object) {
    this._object = _object;
  }


  public TransfersResponse amount(Long amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Amount in cents of the transfer.
   * @return amount
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(Long amount) {
    this.amount = amount;
  }


  public TransfersResponse createdAt(Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Date and time of creation of the transfer in Unix format.
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(Long createdAt) {
    this.createdAt = createdAt;
  }


  public TransfersResponse currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * The currency of the transfer. It uses the 3-letter code of ISO 4217.
   * @return currency
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public TransfersResponse livemode(Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

   /**
   * Indicates whether the transfer was created in live mode or test mode.
   * @return livemode
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LIVEMODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getLivemode() {
    return livemode;
  }


  @JsonProperty(JSON_PROPERTY_LIVEMODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLivemode(Boolean livemode) {
    this.livemode = livemode;
  }


  public TransfersResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Code indicating transfer status.
   * @return status
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  public TransfersResponse statementReference(String statementReference) {
    this.statementReference = statementReference;
    return this;
  }

   /**
   * Reference number of the transfer.
   * @return statementReference
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATEMENT_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatementReference() {
    return statementReference;
  }


  @JsonProperty(JSON_PROPERTY_STATEMENT_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatementReference(String statementReference) {
    this.statementReference = statementReference;
  }


  public TransfersResponse statementDescription(String statementDescription) {
    this.statementDescription = statementDescription;
    return this;
  }

   /**
   * Description of the transfer.
   * @return statementDescription
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATEMENT_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatementDescription() {
    return statementDescription;
  }


  @JsonProperty(JSON_PROPERTY_STATEMENT_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatementDescription(String statementDescription) {
    this.statementDescription = statementDescription;
  }


  public TransfersResponse destination(TransfersResponseDestination destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransfersResponseDestination getDestination() {
    return destination;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestination(TransfersResponseDestination destination) {
    this.destination = destination;
  }


  public TransfersResponse fee(Long fee) {
    this.fee = fee;
    return this;
  }

   /**
   * Total fee for the transfer (present only when requesting the &#39;details&#39; expansion).
   * @return fee
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getFee() {
    return fee;
  }


  @JsonProperty(JSON_PROPERTY_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFee(Long fee) {
    this.fee = fee;
  }


  public TransfersResponse captureAmount(Long captureAmount) {
    this.captureAmount = captureAmount;
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return captureAmount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPTURE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCaptureAmount() {
    return captureAmount;
  }


  @JsonProperty(JSON_PROPERTY_CAPTURE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaptureAmount(Long captureAmount) {
    this.captureAmount = captureAmount;
  }


  public TransfersResponse captureFee(Long captureFee) {
    this.captureFee = captureFee;
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return captureFee
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPTURE_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCaptureFee() {
    return captureFee;
  }


  @JsonProperty(JSON_PROPERTY_CAPTURE_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaptureFee(Long captureFee) {
    this.captureFee = captureFee;
  }


  public TransfersResponse captureNet(Long captureNet) {
    this.captureNet = captureNet;
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return captureNet
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPTURE_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCaptureNet() {
    return captureNet;
  }


  @JsonProperty(JSON_PROPERTY_CAPTURE_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaptureNet(Long captureNet) {
    this.captureNet = captureNet;
  }


  public TransfersResponse refundAmount(Long refundAmount) {
    this.refundAmount = refundAmount;
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return refundAmount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFUND_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRefundAmount() {
    return refundAmount;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundAmount(Long refundAmount) {
    this.refundAmount = refundAmount;
  }


  public TransfersResponse refundFee(Long refundFee) {
    this.refundFee = refundFee;
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return refundFee
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFUND_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRefundFee() {
    return refundFee;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundFee(Long refundFee) {
    this.refundFee = refundFee;
  }


  public TransfersResponse refundNet(Long refundNet) {
    this.refundNet = refundNet;
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return refundNet
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFUND_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRefundNet() {
    return refundNet;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundNet(Long refundNet) {
    this.refundNet = refundNet;
  }


  public TransfersResponse payoutAmount(Long payoutAmount) {
    this.payoutAmount = payoutAmount;
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return payoutAmount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYOUT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPayoutAmount() {
    return payoutAmount;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutAmount(Long payoutAmount) {
    this.payoutAmount = payoutAmount;
  }


  public TransfersResponse payoutFee(Long payoutFee) {
    this.payoutFee = payoutFee;
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return payoutFee
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYOUT_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPayoutFee() {
    return payoutFee;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutFee(Long payoutFee) {
    this.payoutFee = payoutFee;
  }


  public TransfersResponse payoutNet(Long payoutNet) {
    this.payoutNet = payoutNet;
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return payoutNet
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYOUT_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPayoutNet() {
    return payoutNet;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutNet(Long payoutNet) {
    this.payoutNet = payoutNet;
  }


  public TransfersResponse transactions(List<Object> transactions) {
    this.transactions = transactions;
    return this;
  }

  public TransfersResponse addTransactionsItem(Object transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * Present only when requesting the &#39;details&#39; expansion.
   * @return transactions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getTransactions() {
    return transactions;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactions(List<Object> transactions) {
    this.transactions = transactions;
  }


  /**
   * Return true if this transfers_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransfersResponse transfersResponse = (TransfersResponse) o;
    return Objects.equals(this.id, transfersResponse.id) &&
        Objects.equals(this._object, transfersResponse._object) &&
        Objects.equals(this.amount, transfersResponse.amount) &&
        Objects.equals(this.createdAt, transfersResponse.createdAt) &&
        Objects.equals(this.currency, transfersResponse.currency) &&
        Objects.equals(this.livemode, transfersResponse.livemode) &&
        Objects.equals(this.status, transfersResponse.status) &&
        Objects.equals(this.statementReference, transfersResponse.statementReference) &&
        Objects.equals(this.statementDescription, transfersResponse.statementDescription) &&
        Objects.equals(this.destination, transfersResponse.destination) &&
        Objects.equals(this.fee, transfersResponse.fee) &&
        Objects.equals(this.captureAmount, transfersResponse.captureAmount) &&
        Objects.equals(this.captureFee, transfersResponse.captureFee) &&
        Objects.equals(this.captureNet, transfersResponse.captureNet) &&
        Objects.equals(this.refundAmount, transfersResponse.refundAmount) &&
        Objects.equals(this.refundFee, transfersResponse.refundFee) &&
        Objects.equals(this.refundNet, transfersResponse.refundNet) &&
        Objects.equals(this.payoutAmount, transfersResponse.payoutAmount) &&
        Objects.equals(this.payoutFee, transfersResponse.payoutFee) &&
        Objects.equals(this.payoutNet, transfersResponse.payoutNet) &&
        Objects.equals(this.transactions, transfersResponse.transactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, amount, createdAt, currency, livemode, status, statementReference, statementDescription, destination, fee, captureAmount, captureFee, captureNet, refundAmount, refundFee, refundNet, payoutAmount, payoutFee, payoutNet, transactions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransfersResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statementReference: ").append(toIndentedString(statementReference)).append("\n");
    sb.append("    statementDescription: ").append(toIndentedString(statementDescription)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    captureAmount: ").append(toIndentedString(captureAmount)).append("\n");
    sb.append("    captureFee: ").append(toIndentedString(captureFee)).append("\n");
    sb.append("    captureNet: ").append(toIndentedString(captureNet)).append("\n");
    sb.append("    refundAmount: ").append(toIndentedString(refundAmount)).append("\n");
    sb.append("    refundFee: ").append(toIndentedString(refundFee)).append("\n");
    sb.append("    refundNet: ").append(toIndentedString(refundNet)).append("\n");
    sb.append("    payoutAmount: ").append(toIndentedString(payoutAmount)).append("\n");
    sb.append("    payoutFee: ").append(toIndentedString(payoutFee)).append("\n");
    sb.append("    payoutNet: ").append(toIndentedString(payoutNet)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
