/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;


/**
 * Destination payout method used to make the transfer.
 */
@JsonPropertyOrder({
  TransfersResponseDestination.JSON_PROPERTY_PAYEE_ID,
  TransfersResponseDestination.JSON_PROPERTY_ID,
  TransfersResponseDestination.JSON_PROPERTY_CREATED_AT,
  TransfersResponseDestination.JSON_PROPERTY_OBJECT,
  TransfersResponseDestination.JSON_PROPERTY_TYPE,
  TransfersResponseDestination.JSON_PROPERTY_LAST4,
  TransfersResponseDestination.JSON_PROPERTY_ACCOUNT_HOLDER_NAME,
  TransfersResponseDestination.JSON_PROPERTY_BANK
})
@JsonTypeName("transfers_response_destination")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class TransfersResponseDestination {
  public static final String JSON_PROPERTY_PAYEE_ID = "payee_id";
  private String payeeId;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private Long createdAt;

  public static final String JSON_PROPERTY_OBJECT = "object";
  private String _object;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_LAST4 = "last4";
  private String last4;

  public static final String JSON_PROPERTY_ACCOUNT_HOLDER_NAME = "account_holder_name";
  private String accountHolderName;

  public static final String JSON_PROPERTY_BANK = "bank";
  private String bank;

  public TransfersResponseDestination() { 
  }

  public TransfersResponseDestination payeeId(String payeeId) {
    this.payeeId = payeeId;
    return this;
  }

   /**
   * Unique identifier of the payee.
   * @return payeeId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYEE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPayeeId() {
    return payeeId;
  }


  @JsonProperty(JSON_PROPERTY_PAYEE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayeeId(String payeeId) {
    this.payeeId = payeeId;
  }


  public TransfersResponseDestination id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the payout method.
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public TransfersResponseDestination createdAt(Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Date and time of creation of the payout method in Unix format.
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(Long createdAt) {
    this.createdAt = createdAt;
  }


  public TransfersResponseDestination _object(String _object) {
    this._object = _object;
    return this;
  }

   /**
   * Object name, present for bank transfer destination.
   * @return _object
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(String _object) {
    this._object = _object;
  }


  public TransfersResponseDestination type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Destination type.
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public TransfersResponseDestination last4(String last4) {
    this.last4 = last4;
    return this;
  }

   /**
   * Last 4 digits of the destination account number.
   * @return last4
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLast4() {
    return last4;
  }


  @JsonProperty(JSON_PROPERTY_LAST4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast4(String last4) {
    this.last4 = last4;
  }


  public TransfersResponseDestination accountHolderName(String accountHolderName) {
    this.accountHolderName = accountHolderName;
    return this;
  }

   /**
   * Name of the account holder.
   * @return accountHolderName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountHolderName() {
    return accountHolderName;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountHolderName(String accountHolderName) {
    this.accountHolderName = accountHolderName;
  }


  public TransfersResponseDestination bank(String bank) {
    this.bank = bank;
    return this;
  }

   /**
   * Name of the bank.
   * @return bank
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBank() {
    return bank;
  }


  @JsonProperty(JSON_PROPERTY_BANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBank(String bank) {
    this.bank = bank;
  }


  /**
   * Return true if this transfers_response_destination object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransfersResponseDestination transfersResponseDestination = (TransfersResponseDestination) o;
    return Objects.equals(this.payeeId, transfersResponseDestination.payeeId) &&
        Objects.equals(this.id, transfersResponseDestination.id) &&
        Objects.equals(this.createdAt, transfersResponseDestination.createdAt) &&
        Objects.equals(this._object, transfersResponseDestination._object) &&
        Objects.equals(this.type, transfersResponseDestination.type) &&
        Objects.equals(this.last4, transfersResponseDestination.last4) &&
        Objects.equals(this.accountHolderName, transfersResponseDestination.accountHolderName) &&
        Objects.equals(this.bank, transfersResponseDestination.bank);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payeeId, id, createdAt, _object, type, last4, accountHolderName, bank);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransfersResponseDestination {\n");
    sb.append("    payeeId: ").append(toIndentedString(payeeId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    last4: ").append(toIndentedString(last4)).append("\n");
    sb.append("    accountHolderName: ").append(toIndentedString(accountHolderName)).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
