/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;


/**
 * Request body to update a customer.
 */
@JsonPropertyOrder({
  UpdateCustomer.JSON_PROPERTY_NAME,
  UpdateCustomer.JSON_PROPERTY_EMAIL,
  UpdateCustomer.JSON_PROPERTY_PHONE,
  UpdateCustomer.JSON_PROPERTY_CORPORATE,
  UpdateCustomer.JSON_PROPERTY_CUSTOM_REFERENCE,
  UpdateCustomer.JSON_PROPERTY_REFERRER,
  UpdateCustomer.JSON_PROPERTY_METADATA,
  UpdateCustomer.JSON_PROPERTY_PAYMENT_SOURCES,
  UpdateCustomer.JSON_PROPERTY_DEFAULT_PAYMENT_SOURCE_ID,
  UpdateCustomer.JSON_PROPERTY_DEFAULT_FISCAL_ENTITY_ID,
  UpdateCustomer.JSON_PROPERTY_DEFAULT_SHIPPING_CONTACT_ID
})
@JsonTypeName("update_customer")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class UpdateCustomer {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  public static final String JSON_PROPERTY_CORPORATE = "corporate";
  private Boolean corporate = false;

  public static final String JSON_PROPERTY_CUSTOM_REFERENCE = "custom_reference";
  private String customReference;

  public static final String JSON_PROPERTY_REFERRER = "referrer";
  private String referrer;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_PAYMENT_SOURCES = "payment_sources";
  private List<CustomerPaymentMethodsRequest> paymentSources;

  public static final String JSON_PROPERTY_DEFAULT_PAYMENT_SOURCE_ID = "default_payment_source_id";
  private String defaultPaymentSourceId;

  public static final String JSON_PROPERTY_DEFAULT_FISCAL_ENTITY_ID = "default_fiscal_entity_id";
  private String defaultFiscalEntityId;

  public static final String JSON_PROPERTY_DEFAULT_SHIPPING_CONTACT_ID = "default_shipping_contact_id";
  private String defaultShippingContactId;

  public UpdateCustomer() { 
  }

  public UpdateCustomer name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Customer&#39;s name.
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public UpdateCustomer email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Customer email address.
   * @return email
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }


  public UpdateCustomer phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Customer phone number.
   * @return phone
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(String phone) {
    this.phone = phone;
  }


  public UpdateCustomer corporate(Boolean corporate) {
    this.corporate = corporate;
    return this;
  }

   /**
   * Indicates whether the customer email is corporate.
   * @return corporate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CORPORATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCorporate() {
    return corporate;
  }


  @JsonProperty(JSON_PROPERTY_CORPORATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCorporate(Boolean corporate) {
    this.corporate = corporate;
  }


  public UpdateCustomer customReference(String customReference) {
    this.customReference = customReference;
    return this;
  }

   /**
   * Merchant-defined reference used to identify the customer in your system.
   * @return customReference
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomReference() {
    return customReference;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomReference(String customReference) {
    this.customReference = customReference;
  }


  public UpdateCustomer referrer(String referrer) {
    this.referrer = referrer;
    return this;
  }

   /**
   * Referrer value (if applicable).
   * @return referrer
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERRER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferrer() {
    return referrer;
  }


  @JsonProperty(JSON_PROPERTY_REFERRER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferrer(String referrer) {
    this.referrer = referrer;
  }


  public UpdateCustomer metadata(Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public UpdateCustomer putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Arbitrary metadata associated with the customer.
   * @return metadata
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public UpdateCustomer paymentSources(List<CustomerPaymentMethodsRequest> paymentSources) {
    this.paymentSources = paymentSources;
    return this;
  }

  public UpdateCustomer addPaymentSourcesItem(CustomerPaymentMethodsRequest paymentSourcesItem) {
    if (this.paymentSources == null) {
      this.paymentSources = new ArrayList<>();
    }
    this.paymentSources.add(paymentSourcesItem);
    return this;
  }

   /**
   * Contains details of the payment methods that the customer has active or has used in Femsa
   * @return paymentSources
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomerPaymentMethodsRequest> getPaymentSources() {
    return paymentSources;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentSources(List<CustomerPaymentMethodsRequest> paymentSources) {
    this.paymentSources = paymentSources;
  }


  public UpdateCustomer defaultPaymentSourceId(String defaultPaymentSourceId) {
    this.defaultPaymentSourceId = defaultPaymentSourceId;
    return this;
  }

   /**
   * Sets the default payment source for the customer (must be an existing payment source on the customer).
   * @return defaultPaymentSourceId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_PAYMENT_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultPaymentSourceId() {
    return defaultPaymentSourceId;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_PAYMENT_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultPaymentSourceId(String defaultPaymentSourceId) {
    this.defaultPaymentSourceId = defaultPaymentSourceId;
  }


  public UpdateCustomer defaultFiscalEntityId(String defaultFiscalEntityId) {
    this.defaultFiscalEntityId = defaultFiscalEntityId;
    return this;
  }

   /**
   * Sets the default fiscal entity for the customer (must be an existing fiscal entity on the customer).
   * @return defaultFiscalEntityId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_FISCAL_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultFiscalEntityId() {
    return defaultFiscalEntityId;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_FISCAL_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultFiscalEntityId(String defaultFiscalEntityId) {
    this.defaultFiscalEntityId = defaultFiscalEntityId;
  }


  public UpdateCustomer defaultShippingContactId(String defaultShippingContactId) {
    this.defaultShippingContactId = defaultShippingContactId;
    return this;
  }

   /**
   * Sets the default shipping contact for the customer (must be an existing shipping contact on the customer).
   * @return defaultShippingContactId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_SHIPPING_CONTACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultShippingContactId() {
    return defaultShippingContactId;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_SHIPPING_CONTACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultShippingContactId(String defaultShippingContactId) {
    this.defaultShippingContactId = defaultShippingContactId;
  }


  /**
   * Return true if this update_customer object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCustomer updateCustomer = (UpdateCustomer) o;
    return Objects.equals(this.name, updateCustomer.name) &&
        Objects.equals(this.email, updateCustomer.email) &&
        Objects.equals(this.phone, updateCustomer.phone) &&
        Objects.equals(this.corporate, updateCustomer.corporate) &&
        Objects.equals(this.customReference, updateCustomer.customReference) &&
        Objects.equals(this.referrer, updateCustomer.referrer) &&
        Objects.equals(this.metadata, updateCustomer.metadata) &&
        Objects.equals(this.paymentSources, updateCustomer.paymentSources) &&
        Objects.equals(this.defaultPaymentSourceId, updateCustomer.defaultPaymentSourceId) &&
        Objects.equals(this.defaultFiscalEntityId, updateCustomer.defaultFiscalEntityId) &&
        Objects.equals(this.defaultShippingContactId, updateCustomer.defaultShippingContactId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, email, phone, corporate, customReference, referrer, metadata, paymentSources, defaultPaymentSourceId, defaultFiscalEntityId, defaultShippingContactId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCustomer {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    corporate: ").append(toIndentedString(corporate)).append("\n");
    sb.append("    customReference: ").append(toIndentedString(customReference)).append("\n");
    sb.append("    referrer: ").append(toIndentedString(referrer)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    paymentSources: ").append(toIndentedString(paymentSources)).append("\n");
    sb.append("    defaultPaymentSourceId: ").append(toIndentedString(defaultPaymentSourceId)).append("\n");
    sb.append("    defaultFiscalEntityId: ").append(toIndentedString(defaultFiscalEntityId)).append("\n");
    sb.append("    defaultShippingContactId: ").append(toIndentedString(defaultShippingContactId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
