/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;


/**
 * UpdatePaymentMethods
 */
@JsonPropertyOrder({
  UpdatePaymentMethods.JSON_PROPERTY_EXPIRES_AT,
  UpdatePaymentMethods.JSON_PROPERTY_AMOUNT,
  UpdatePaymentMethods.JSON_PROPERTY_TYPE
})
@JsonTypeName("update_payment_methods")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class UpdatePaymentMethods {
  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  private UpdatePaymentMethodsExpiresAt expiresAt;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private UpdatePaymentMethodsAmount amount;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public UpdatePaymentMethods() { 
  }

  public UpdatePaymentMethods expiresAt(UpdatePaymentMethodsExpiresAt expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdatePaymentMethodsExpiresAt getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(UpdatePaymentMethodsExpiresAt expiresAt) {
    this.expiresAt = expiresAt;
  }


  public UpdatePaymentMethods amount(UpdatePaymentMethodsAmount amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdatePaymentMethodsAmount getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(UpdatePaymentMethodsAmount amount) {
    this.amount = amount;
  }


  public UpdatePaymentMethods type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  /**
   * Return true if this update_payment_methods object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePaymentMethods updatePaymentMethods = (UpdatePaymentMethods) o;
    return Objects.equals(this.expiresAt, updatePaymentMethods.expiresAt) &&
        Objects.equals(this.amount, updatePaymentMethods.amount) &&
        Objects.equals(this.type, updatePaymentMethods.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiresAt, amount, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePaymentMethods {\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
