/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.digitalfemsa.JSON;

import javax.ws.rs.core.GenericType;
import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
@JsonDeserialize(using = UpdatePaymentMethodsExpiresAt.UpdatePaymentMethodsExpiresAtDeserializer.class)
@JsonSerialize(using = UpdatePaymentMethodsExpiresAt.UpdatePaymentMethodsExpiresAtSerializer.class)
public class UpdatePaymentMethodsExpiresAt extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(UpdatePaymentMethodsExpiresAt.class.getName());

    public static class UpdatePaymentMethodsExpiresAtSerializer extends StdSerializer<UpdatePaymentMethodsExpiresAt> {
        public UpdatePaymentMethodsExpiresAtSerializer(Class<UpdatePaymentMethodsExpiresAt> t) {
            super(t);
        }

        public UpdatePaymentMethodsExpiresAtSerializer() {
            this(null);
        }

        @Override
        public void serialize(UpdatePaymentMethodsExpiresAt value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class UpdatePaymentMethodsExpiresAtDeserializer extends StdDeserializer<UpdatePaymentMethodsExpiresAt> {
        public UpdatePaymentMethodsExpiresAtDeserializer() {
            this(UpdatePaymentMethodsExpiresAt.class);
        }

        public UpdatePaymentMethodsExpiresAtDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public UpdatePaymentMethodsExpiresAt deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize Long
            try {
                boolean attemptParsing = true;
                attemptParsing = typeCoercion; //respect type coercion setting
                if (!attemptParsing) {
                    attemptParsing |= (token == JsonToken.VALUE_NUMBER_INT);
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Long.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Long'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Long'", e);
            }

            // deserialize String
            try {
                boolean attemptParsing = true;
                attemptParsing = typeCoercion; //respect type coercion setting
                if (!attemptParsing) {
                    attemptParsing |= (token == JsonToken.VALUE_STRING);
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(String.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'String'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'String'", e);
            }

            if (match == 1) {
                UpdatePaymentMethodsExpiresAt ret = new UpdatePaymentMethodsExpiresAt();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for UpdatePaymentMethodsExpiresAt: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public UpdatePaymentMethodsExpiresAt getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "UpdatePaymentMethodsExpiresAt cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<>();

    public UpdatePaymentMethodsExpiresAt() {
        super("oneOf", Boolean.FALSE);
    }

    public UpdatePaymentMethodsExpiresAt(Long o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public UpdatePaymentMethodsExpiresAt(String o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Long", new GenericType<Long>() {
        });
        schemas.put("String", new GenericType<String>() {
        });
        JSON.registerDescendants(UpdatePaymentMethodsExpiresAt.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return UpdatePaymentMethodsExpiresAt.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * Long, String
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(Long.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(String.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Long, String");
    }

    /**
     * Get the actual instance, which can be the following:
     * Long, String
     *
     * @return The actual instance (Long, String)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Long`. If the actual instance is not `Long`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Long`
     * @throws ClassCastException if the instance is not `Long`
     */
    public Long getLong() throws ClassCastException {
        return (Long)super.getActualInstance();
    }

    /**
     * Get the actual instance of `String`. If the actual instance is not `String`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `String`
     * @throws ClassCastException if the instance is not `String`
     */
    public String getString() throws ClassCastException {
        return (String)super.getActualInstance();
    }

}
