/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;


/**
 * Represents a webhook signing key after it has been deleted.
 */
@JsonPropertyOrder({
  WebhookKeyDeleteResponse.JSON_PROPERTY_ID,
  WebhookKeyDeleteResponse.JSON_PROPERTY_OBJECT,
  WebhookKeyDeleteResponse.JSON_PROPERTY_ACTIVE,
  WebhookKeyDeleteResponse.JSON_PROPERTY_LIVEMODE,
  WebhookKeyDeleteResponse.JSON_PROPERTY_CREATED_AT,
  WebhookKeyDeleteResponse.JSON_PROPERTY_DEACTIVATED_AT,
  WebhookKeyDeleteResponse.JSON_PROPERTY_DELETED
})
@JsonTypeName("webhook-key_delete_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class WebhookKeyDeleteResponse {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_OBJECT = "object";
  private String _object;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_LIVEMODE = "livemode";
  private Boolean livemode;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private Long createdAt;

  public static final String JSON_PROPERTY_DEACTIVATED_AT = "deactivated_at";
  private Long deactivatedAt;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public WebhookKeyDeleteResponse() { 
  }

  public WebhookKeyDeleteResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the webhook key
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public WebhookKeyDeleteResponse _object(String _object) {
    this._object = _object;
    return this;
  }

   /**
   * Object name, value is webhook_key
   * @return _object
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(String _object) {
    this._object = _object;
  }


  public WebhookKeyDeleteResponse active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Indicates if the webhook key is active
   * @return active
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public WebhookKeyDeleteResponse livemode(Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

   /**
   * Indicates if the webhook key is in live mode
   * @return livemode
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LIVEMODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getLivemode() {
    return livemode;
  }


  @JsonProperty(JSON_PROPERTY_LIVEMODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLivemode(Boolean livemode) {
    this.livemode = livemode;
  }


  public WebhookKeyDeleteResponse createdAt(Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Unix timestamp in seconds with the creation date of the webhook key
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(Long createdAt) {
    this.createdAt = createdAt;
  }


  public WebhookKeyDeleteResponse deactivatedAt(Long deactivatedAt) {
    this.deactivatedAt = deactivatedAt;
    return this;
  }

   /**
   * Unix timestamp in seconds when the webhook key was deactivated (if applicable).
   * @return deactivatedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEACTIVATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDeactivatedAt() {
    return deactivatedAt;
  }


  @JsonProperty(JSON_PROPERTY_DEACTIVATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeactivatedAt(Long deactivatedAt) {
    this.deactivatedAt = deactivatedAt;
  }


  public WebhookKeyDeleteResponse deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Indicates if the webhook key is deleted
   * @return deleted
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  /**
   * Return true if this webhook-key_delete_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookKeyDeleteResponse webhookKeyDeleteResponse = (WebhookKeyDeleteResponse) o;
    return Objects.equals(this.id, webhookKeyDeleteResponse.id) &&
        Objects.equals(this._object, webhookKeyDeleteResponse._object) &&
        Objects.equals(this.active, webhookKeyDeleteResponse.active) &&
        Objects.equals(this.livemode, webhookKeyDeleteResponse.livemode) &&
        Objects.equals(this.createdAt, webhookKeyDeleteResponse.createdAt) &&
        Objects.equals(this.deactivatedAt, webhookKeyDeleteResponse.deactivatedAt) &&
        Objects.equals(this.deleted, webhookKeyDeleteResponse.deleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, active, livemode, createdAt, deactivatedAt, deleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookKeyDeleteResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deactivatedAt: ").append(toIndentedString(deactivatedAt)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
