/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for ApiKeysApi
 */
public class ApiKeysApiTest {

    private final ApiKeysApi api = new ApiKeysApi();

    /**
     * Create Api Key
     *
     * Create a api key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createApiKeyTest() throws ApiException {
        //ApiKeyRequest apiKeyRequest = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ApiKeyCreateResponse response = api.createApiKey(apiKeyRequest, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Delete Api Key
     *
     * Deletes a api key that corresponds to a api key ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteApiKeyTest() throws ApiException {
        //String id = null;
        //String acceptLanguage = null;
        //DeleteApiKeysResponse response = api.deleteApiKey(id, acceptLanguage);
        // TODO: test validations
    }

    /**
     * Get Api Key
     *
     * Gets a api key that corresponds to a api key ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getApiKeyTest() throws ApiException {
        //String id = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ApiKeyResponse response = api.getApiKey(id, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Get list of Api Keys
     *
     * Consume the list of api keys you have
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getApiKeysTest() throws ApiException {
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //Integer limit = null;
        //String next = null;
        //String previous = null;
        //String search = null;
        //GetApiKeysResponse response = api.getApiKeys(acceptLanguage, xChildCompanyId, limit, next, previous, search);
        // TODO: test validations
    }

    /**
     * Update Api Key
     *
     * Update an existing api key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateApiKeyTest() throws ApiException {
        //String id = null;
        //String acceptLanguage = null;
        //ApiKeyUpdateRequest apiKeyUpdateRequest = null;
        //ApiKeyResponse response = api.updateApiKey(id, acceptLanguage, apiKeyUpdateRequest);
        // TODO: test validations
    }

}
