/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for BalancesApi
 */
public class BalancesApiTest {

    private final BalancesApi api = new BalancesApi();

    /**
     * Get a company&#39;s balance
     *
     * Get a company&#39;s balance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBalanceTest() throws ApiException {
        //String acceptLanguage = null;
        //BalanceResponse response = api.getBalance(acceptLanguage);
        // TODO: test validations
    }

}
