/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for CompaniesApi
 */
public class CompaniesApiTest {

    private final CompaniesApi api = new CompaniesApi();

    /**
     * Get List of Companies
     *
     * Consume the list of child companies.  This is used for holding companies with several child entities.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCompaniesTest() throws ApiException {
        //String acceptLanguage = null;
        //Integer limit = null;
        //String search = null;
        //String next = null;
        //String previous = null;
        //GetCompaniesResponse response = api.getCompanies(acceptLanguage, limit, search, next, previous);
        // TODO: test validations
    }

    /**
     * Get Company
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCompanyTest() throws ApiException {
        //String id = null;
        //String acceptLanguage = null;
        //CompanyResponse response = api.getCompany(id, acceptLanguage);
        // TODO: test validations
    }

}
