/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for DiscountsApi
 */
public class DiscountsApiTest {

    private final DiscountsApi api = new DiscountsApi();

    /**
     * Create Discount
     *
     * Create discount lines for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersCreateDiscountLineTest() throws ApiException {
        //String id = null;
        //OrderDiscountLinesRequest orderDiscountLinesRequest = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //DiscountLinesResponse response = api.ordersCreateDiscountLine(id, orderDiscountLinesRequest, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Delete Discount
     *
     * Delete an existing discount lines for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersDeleteDiscountLinesTest() throws ApiException {
        //String id = null;
        //String discountLinesId = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //DiscountLinesResponse response = api.ordersDeleteDiscountLines(id, discountLinesId, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Get Discount
     *
     * Get an existing discount lines for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersGetDiscountLineTest() throws ApiException {
        //String id = null;
        //String discountLinesId = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //DiscountLinesResponse response = api.ordersGetDiscountLine(id, discountLinesId, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Get a List of Discount
     *
     * Get discount lines for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersGetDiscountLinesTest() throws ApiException {
        //String id = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //Integer limit = null;
        //String search = null;
        //String next = null;
        //String previous = null;
        //GetOrderDiscountLinesResponse response = api.ordersGetDiscountLines(id, acceptLanguage, xChildCompanyId, limit, search, next, previous);
        // TODO: test validations
    }

    /**
     * Update Discount
     *
     * Update an existing discount lines for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersUpdateDiscountLinesTest() throws ApiException {
        //String id = null;
        //String discountLinesId = null;
        //UpdateOrderDiscountLinesRequest updateOrderDiscountLinesRequest = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //DiscountLinesResponse response = api.ordersUpdateDiscountLines(id, discountLinesId, updateOrderDiscountLinesRequest, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

}
