/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for EventsApi
 */
public class EventsApiTest {

    private final EventsApi api = new EventsApi();

    /**
     * Get Event
     *
     * Returns a single event
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventTest() throws ApiException {
        //String id = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //EventResponse response = api.getEvent(id, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Get list of Events
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventsTest() throws ApiException {
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //Integer limit = null;
        //String search = null;
        //String next = null;
        //String previous = null;
        //GetEventsResponse response = api.getEvents(acceptLanguage, xChildCompanyId, limit, search, next, previous);
        // TODO: test validations
    }

    /**
     * Resend Event
     *
     * Try to send an event
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resendEventTest() throws ApiException {
        //String eventId = null;
        //String webhookLogId = null;
        //String acceptLanguage = null;
        //EventsResendResponse response = api.resendEvent(eventId, webhookLogId, acceptLanguage);
        // TODO: test validations
    }

}
