/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for LogsApi
 */
public class LogsApiTest {

    private final LogsApi api = new LogsApi();

    /**
     * Get Log
     *
     * Get the details of a specific log
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLogByIdTest() throws ApiException {
        //String id = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //LogResponse response = api.getLogById(id, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Get List Of Logs
     *
     * Get log details in the form of a list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLogsTest() throws ApiException {
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //Integer limit = null;
        //String search = null;
        //String next = null;
        //String previous = null;
        //LogsResponse response = api.getLogs(acceptLanguage, xChildCompanyId, limit, search, next, previous);
        // TODO: test validations
    }

}
