/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for ProductsApi
 */
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * Create Product
     *
     * Create a new product for an existing order.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersCreateProductTest() throws ApiException {
        //String id = null;
        //Product product = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ProductOrderResponse response = api.ordersCreateProduct(id, product, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Delete Product
     *
     * Delete product for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersDeleteProductTest() throws ApiException {
        //String id = null;
        //String lineItemId = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ProductOrderResponse response = api.ordersDeleteProduct(id, lineItemId, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Update Product
     *
     * Update an existing product for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersUpdateProductTest() throws ApiException {
        //String id = null;
        //String lineItemId = null;
        //UpdateProduct updateProduct = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ProductOrderResponse response = api.ordersUpdateProduct(id, lineItemId, updateProduct, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

}
