/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for ShippingsApi
 */
public class ShippingsApiTest {

    private final ShippingsApi api = new ShippingsApi();

    /**
     * Create Shipping
     *
     * Create new shipping for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersCreateShippingTest() throws ApiException {
        //String id = null;
        //ShippingRequest shippingRequest = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ShippingOrderResponse response = api.ordersCreateShipping(id, shippingRequest, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Delete Shipping
     *
     * Delete shipping
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersDeleteShippingTest() throws ApiException {
        //String id = null;
        //String shippingId = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ShippingOrderResponse response = api.ordersDeleteShipping(id, shippingId, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Update Shipping
     *
     * Update existing shipping for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersUpdateShippingTest() throws ApiException {
        //String id = null;
        //String shippingId = null;
        //ShippingRequest shippingRequest = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ShippingOrderResponse response = api.ordersUpdateShipping(id, shippingId, shippingRequest, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

}
