/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for TaxesApi
 */
public class TaxesApiTest {

    private final TaxesApi api = new TaxesApi();

    /**
     * Create Tax
     *
     * Create new taxes for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersCreateTaxesTest() throws ApiException {
        //String id = null;
        //OrderTaxRequest orderTaxRequest = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //UpdateOrderTaxResponse response = api.ordersCreateTaxes(id, orderTaxRequest, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Delete Tax
     *
     * Delete taxes for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersDeleteTaxesTest() throws ApiException {
        //String id = null;
        //String taxId = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //UpdateOrderTaxResponse response = api.ordersDeleteTaxes(id, taxId, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Update Tax
     *
     * Update taxes for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersUpdateTaxesTest() throws ApiException {
        //String id = null;
        //String taxId = null;
        //UpdateOrderTaxRequest updateOrderTaxRequest = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //UpdateOrderTaxResponse response = api.ordersUpdateTaxes(id, taxId, updateOrderTaxRequest, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

}
