/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import org.junit.jupiter.api.Test;

/**
 * API tests for TransactionsApi
 */
public class TransactionsApiTest {

    private final TransactionsApi api = new TransactionsApi();

    /**
     * Get transaction
     *
     * Get the details of a transaction
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTransactionTest() throws ApiException {
        //String id = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //TransactionResponse response = api.getTransaction(id, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Get List transactions
     *
     * Get transaction details in the form of a list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTransactionsTest() throws ApiException {
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //Integer limit = null;
        //String next = null;
        //String previous = null;
        //String id = null;
        //String chargeId = null;
        //String type = null;
        //String currency = null;
        //GetTransactionsResponse response = api.getTransactions(acceptLanguage, xChildCompanyId, limit, next, previous, id, chargeId, type, currency);
        // TODO: test validations
    }

}
